//
// Created by 刘一辰 on 2021/1/9.
//

#ifndef SPLATDEMO_DEFINELIST_H
#define SPLATDEMO_DEFINELIST_H

#define FLOOR_SIZE 300
#define FLOOR_MAX_POSITION 50
#define FLOOR_UNIT (2.0*FLOOR_MAX_POSITION/FLOOR_SIZE)
#define FLOOR_COLOR 0.6
#define GET_POS(x,y) ((x)*(FLOOR_SIZE+1)+(y))
#define OUT_RADIUS 5
#define IN_RADIUS 2

#endif //SPLATDEMO_DEFINELIST_H
